arb-dir: lib/l10n
template-arb-file: app_en.arb
output-class: AppLocalizations
output-dir: lib/l10n/generated
synthetic-package: false   # put generated file where you can import it
preferred-supported-locales: [en, ru]